#!/bin/bash

yum install google-cloud-sdk                         #install google-cloud-sdk   
gcloud init                                          # takes you through gcloud configration and you have to type yes(y) to continou the confegeration.

yum install python-pip                               #pip installing paython module 
pip install --upgrade pip                            #upgrading pip pythone                        
 pip install oauth2client                            #pip install oauth2client 
 
pip install --upgrade google-api-python-client                     # list all the instance in gcloud compute
gcloud compute instances list                                      #it list all the instances in gcloud
yum install git                                                    #install git
git clone //https://github.com/nic-instruction/NTI-300-2017.git    #this Git command line utility which is used to target an existing repository and create a clone, or copy of the target repository

cd NTI-300-2017                                                    #change your directory to the cloned respairatory 
ls -l
cd gcloud                                                          #change the directory to gcloud
ls                                                                 #list all fill


